<!DOCTYPE html>
<html lang="en">
<!-- Navbar -->
<?php require "public/head.phtml"; ?>

<body class="bg-gray-100">

<!-- Navbar -->
<?php require "public/navigation.phtml"; ?>

<!-- Main Content -->
<main class="container mx-auto md:max-w-screen-xl mt-8 px-4">
    <div class="flex flex-col md:flex-row justify-between gap:3 lg:gap-8 h-full">
        <?php if(isset($_SESSION['user'])): ?>
            <!-- User Image Section -->
            <section class="mb-2 md:w-4/12 lg:w-1/3 h-min">
                <section class="bg-white rounded-lg p-6 mb-8">
                    <!-- User Image here -->
                    <div class="flex items-center justify-center mb-4">
                        <img src="" alt="User Image" class="w-32 h-32 rounded-full userImg">
                    </div>
                    <!-- User details -->
                    <div class="mb-4 text-center md:text-left">
                        <h2 class="text-lg font-medium mb-2 lg:mb-3 text-center md:text-left">Personal Information</h2>
                        <!-- Populate user details from session -->
                        <p>Name: <span id="userName"><?php echo $_SESSION['user']['full_name']; ?></span></p>
                        <p>Email: <?php echo $_SESSION['user']['email'] ?></p>
                        <p>Member for: <?php echo $_SESSION['membership_duration'] ?></p>
                        <a href="services/user/logout.php" class="inline-block bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 mt-4">
                            Log out
                        </a>
                    </div>
                </section>


            </section>

            <!-- User Profile Section -->
            <section class="bg-white rounded-lg p-6 mb-2 md:text-left md:w-7/12 lg:w-2/3 h-fit">
<!--                <h1 class="text-xl lg:text-2xl font-semibold mb-5">User Profile</h1>-->
                <!-- Subsections -->
                <div class="account-options-navigation flex justify-between mb-4">
                    <!-- Settings Subsection -->
                    <div>
                        <button id="settingsBtn" class="text-md lg:text-lg font-medium mb-2 focus:outline-none border border-indigo-600 'border-2 bg-indigo-100 p-2 rounded-md">Settings</button>
                    </div>
                    <!-- Change Information Subsection -->
                    <div>
                        <button id="changeInfoBtn" class="text-md lg:text-lg font-medium mb-2 focus:outline-none p-2 rounded-md">Change Information</button>
                    </div>
                    <!-- Privacy Subsection -->
                    <div>
                        <button id="privacyBtn" class="text-md lg:text-lg font-medium mb-2 focus:outline-none p-2 rounded-md">Privacy</button>
                    </div>
                </div>
                <hr class="mb-4">
                <!-- Settings Subsection -->
                <section id="settingsSection" class="user-section">
                    <h3 class="text-md lg:text-lg font-medium mb-4">Settings</h3>
                    <form action="services/user/change-settings.php" method="POST">
                        <input name="id" class="hidden" value="<?php echo ($_SESSION['user']['id'])?>"/>
                        <!-- Language Setting -->
                        <div class="mb-4">
                            <label for="language" class="block mb-2 text-md">Language</label>
                            <select id="language" name="language" class="md:w-1/3 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                                <option value="english" <?php echo ($_SESSION['user-settings']['language'] === 'english') ? 'selected' : ''; ?>>English</option>
                                <option value="spanish" <?php echo ($_SESSION['user-settings']['language'] === 'spanish') ? 'selected' : ''; ?>>Spanish</option>
                                <!-- Add more language options as needed -->
                            </select>
                        </div>

                        <!-- Dark/Light Mode Setting -->
                        <div class="mb-4">
                            <label for="theme" class="block mb-2 text-md">Mode</label>
                            <select id="theme" name="theme" class="md:w-1/3 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                                <option value="0" <?php echo ($_SESSION['user-settings']['theme'] === '0') ? 'selected' : ''; ?>>Light</option>
                                <option value="1" <?php echo ($_SESSION['user-settings']['theme'] === '1') ? 'selected' : ''; ?>>Dark</option>
                            </select>
                        </div>

                        <!-- Number of Cards per Row Setting -->
                        <div class="mb-4">
                            <label for="cardsPerRow" class="block mb-2 text-md">Number of Cards per Row</label>
                            <select id="cardsPerRow" name="cards_per_row" class="md:w-1/3 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                                <option value="4" <?php echo ($_SESSION['user-settings']['cards_per_row'] === '4') ? 'selected' : ''; ?>>4</option>
                                <option value="3" <?php echo ($_SESSION['user-settings']['cards_per_row'] === '3') ? 'selected' : ''; ?>>3</option>
                                <!-- Add more options as needed -->
                            </select>
                        </div>

                        <!-- Currency Setting -->
                        <div class="mb-4">
                            <label for="currency" class="block mb-2 text-md">Currency</label>
                            <select id="currency" name="currency" class="md:w-1/3 w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                                <option value="usd" <?php echo ($_SESSION['user-settings']['currency'] === 'usd') ? 'selected' : ''; ?>>USD</option>
                                <option value="eur" <?php echo ($_SESSION['user-settings']['currency'] === 'eur') ? 'selected' : ''; ?>>EUR</option>
                                <!-- Add more options as needed -->
                            </select>
                        </div>


                        <!-- Save Settings Button -->
                        <button type="submit" class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 mt-2">Save Settings</button>
                    </form>





                    <?php if(isset($_SESSION['settings-changed-success'])): ?>
                        <p class="pt-3 text-sm"><?= getFlashMessage('settings-changed-success')?></p>
                    <?php endif;?>
                    <?php if(isset($_SESSION['error'])): ?>
                        <p class="pt-3 text-sm"><?= getFlashMessage('error')?></p>
                    <?php endif;?>



                </section>



                <!-- Change Information Subsection -->
                <section id="changeInfoSection" class="user-section hidden">
                    <form action="#" method="POST">
                        <h3 class="text-md lg:text-lg font-medium mb-4">Change Information</h3>
                        <div class="mb-4">
                            <label for="currentPassword" class="block mb-2 text-md">Current Password</label>
                            <input type="password" id="currentPassword" name="currentPassword" placeholder="Enter current password"
                                   class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                        </div>
                        <div class="mb-4">
                            <label for="newPassword" class="block mb-2 text-md">New Password</label>
                            <input type="password" id="newPassword" name="newPassword" placeholder="Enter new password"
                                   class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                        </div>
                        <button type="submit"
                                class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 mt-2">
                            Change Information
                        </button>
                    </form>
                </section>

                <!-- Change Password Form -->
                <section id="privacySection" class="user-section hidden">
                    <section class="mb-6">
                        <form action="#" method="POST">
                            <h3 class="text-md lg:text-lg font-medium mb-4">Change Password</h3>
                            <p class="text-sm md:text-base mb-5 text-left text-gray-700">To enhance security, please note that password changes are limited to once per week. Thank you for your cooperation in maintaining the integrity of your account.</p>
                            <div class="mb-4">
                                <label for="currentPassword" class="block mb-2 text-md">Current Password</label>
                                <input type="password" id="currentPassword" name="currentPassword" placeholder="Enter current password"
                                       class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                            </div>
                            <div class="mb-4">
                                <label for="newPassword" class="block mb-2 text-md">New Password</label>
                                <input type="password" id="newPassword" name="newPassword" placeholder="Enter new password"
                                       class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                            </div>
                            <div class="mb-4">
                                <label for="confirmPassword" class="block mb-2 text-md">Confirm New Password</label>
                                <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirm new password"
                                       class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500">
                            </div>
                            <button type="submit"
                                    class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 mt-2">
                                Change Password
                            </button>
                        </form>
                    </section>
                    <hr class="mb-4">
                    <section class="mb-7">
                        <h3 class="text-md lg:text-lg font-medium mb-4">Manage Data Sharing</h3>
                        <p class="text-sm md:text-base mb-5 text-left text-gray-700">This feature allows you to control how your personal information is shared with others on the platform. By managing your data sharing preferences, you can customize the level of privacy and visibility for different aspects of your profile.</p>
                        <!-- Switch Toggle 1 -->
                        <div class="flex flex-col md:flex-row gap-5">
                            <!-- Switch Toggle 1 -->

                            <!-- Switch Toggle 1 -->
                            <label class="inline-flex items-center cursor-pointer">
                                <input type="checkbox" value="" class="sr-only peer" checked>
                                <span class="text-sm font-medium text-gray-900 dark:text-gray-300 mr-3">Location Sharing</span>
                                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-indigo-600"></div>
                            </label>

                            <!-- Switch Toggle 2 -->
                            <label class="inline-flex items-center cursor-pointer">
                                <input type="checkbox" value="" class="sr-only peer" checked>
                                <span class="text-sm font-medium text-gray-900 dark:text-gray-300 mr-3">Preferences</span>
                                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-indigo-600"></div>
                            </label>

                            <!-- Switch Toggle 3 -->
                            <label class="inline-flex items-center cursor-pointer">
                                <input type="checkbox" value="" class="sr-only peer" checked>
                                <span class="text-sm font-medium text-gray-900 dark:text-gray-300 mr-3">Third-Party Access</span>
                                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-indigo-600"></div>
                            </label>
                        </div>
                    </section>
                </section>
            </section>
        <?php else: ?>
            <!-- Sign In Prompt -->
            <section class="bg-white rounded-lg p-6 mb-8">
                <h1 class="text-2xl font-semibold mb-4">Sign In Required</h1>
                <p class="mb-4">You must sign in to access your account page.</p>
                <a href="login.php" class="text-indigo-600 hover:underline">Sign In</a>
            </section>
        <?php endif; ?>
    </div>

</main>

<script src="https://cdn.tailwindcss.com/"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const checkboxes = document.querySelectorAll('.toggle-checkbox');
        checkboxes.forEach(function (checkbox) {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    // If checkbox is checked, add 'bg-indigo-600' class to the label
                    this.nextElementSibling.classList.add('bg-indigo-600');
                    // Toggle the switch
                } else {
                    // If checkbox is unchecked, remove 'bg-indigo-600' class from the label
                    this.nextElementSibling.classList.remove('bg-indigo-600');
                    // Toggle the switch
                }
            });
        });
    });

    //const userFullName = <?php //echo json_encode($_SESSION['full_name']); ?>////;

</script>
<script src="public/user/js/account.js"></script>
</body>

</html>
