<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<main class="bg-gray-100 min-h-screen flex items-center justify-center">
    <div class="bg-white mx-auto p-8 rounded-md shadow-md w-full max-w-sm">
        <h1 class="text-2xl font-semibold text-center mb-4">Verification Success</h1>
        <p class="text-gray-700 text-center mb-6">Your email has been successfully verified.</p>
        <div class="flex items-center justify-between">
            <a href="login.php"
               class="bg-indigo-600 mx-auto text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700">
                Go to Login
            </a>
        </div>
    </div>
</main>

</body>

</html>