<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<!-- Navbar -->



<!-- Main Content -->
<main class="bg-gray-100 min-h-screen flex items-center justify-center">
    <div class="bg-white mx-auto p-8 rounded-md shadow-md w-full max-w-sm">
        <h1 class="text-2xl font-semibold text-center mb-4">Email Verification</h1>
        <p class="text-gray-700 text-center mb-6">A verification link has been sent to your email address.</p>
        <div>
            <div class="mb-6">
                <label for="verificationCode" class="block pb-1 text-sm font-medium text-gray-700">Verification Code</label>
                <input type="text" id="verificationCode" name="verificationCode" placeholder="Enter verification code"
                       class="mt-1 p-3 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div class="flex items-center justify-between">
                <button id="verifyCode"
                        class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700">
                    Verify
                </button>
                <a href="" id="resendCode" class="text-sm text-gray-600 hover:text-indigo-600">Resend Code</a>
            </div>
        </div>
        <p class="pt-3 text-sm" id="message"></p>
    </div>
</main>
<script src="public/user/js/email-verification.js"></script>
</body>

</html>
