<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<!-- Navbar -->
<?php require "public/navigation.phtml"; ?>

<!-- Main Content -->
<main class="container justify-between lg mx-auto lg:max-w-screen-xl mt-8 px-4">
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <img class="mx-auto h-10 w-auto" src="public/img/realestate-logo.png" alt="Sevo Real Estate">
            <h2 class="mt-8 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Create an account</h2>
        </div>

        <div class="mt-6 sm:mx-auto sm:w-full sm:max-w-sm">
            <form class="space-y-6" action="services/user/register.php" method="POST">
                <div>
                    <label for="fullname" class="block text-sm font-medium leading-6 text-gray-900">Full Name</label>
                    <div class="mt-2">
                        <input id="fullname" name="fullname" type="text"  class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500 max-w-sm">
                    </div>
                </div>
                <div>
                    <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email address</label>
                    <div class="mt-2">
                        <input id="email" name="email" type="email" autocomplete="email"  class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500 max-w-sm">
                    </div>
                </div>

                <div>
                    <div class="flex items-center justify-between">
                        <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                        <div class="text-sm">
                        </div>
                    </div>
                    <div class="mt-2">
                        <input id="password" name="password" type="password" autocomplete="current-password"  class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500 max-w-sm">
                    </div>
                </div>
                <div>
                    <div class="flex items-center justify-between">
                        <label for="confirm-password" class="block text-sm font-medium leading-6 text-gray-900">Confirm Password</label>
                        <div class="text-sm">
                        </div>
                    </div>
                    <div class="mt-2">
                        <input id="confirm-password" name="confirm_password" type="password" autocomplete="current-password"  class="w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-indigo-500 max-w-sm">
                    </div>
                </div>
                <div>
                    <input type="checkbox" name="agree_terms" id="terms-checkbox">
                    <label for="termsCheckbox" class="text-sm text-gray-700">I accept the Terms and Conditions</label>
                </div>
                <div>
                    <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                        Create an account
                    </button>
                </div>
            </form>
            <p class="pt-4 text-sm text-gray-700">Already have an account? <a href="login.php" class="text-indigo-600 hover:underline">Sign in here</a></p>
            <p class="pt-4 text-sm text-gray-700 text-red-400"><?= getFlashMessage("register-response")?></p>

        </div>
    </div>
</main>
</body>

</html>