<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<main class="bg-gray-100 min-h-screen flex items-center justify-center">
    <div class="bg-white mx-auto p-8 rounded-md shadow-md w-full max-w-sm text-center">
        <h1 class="text-2xl font-semibold mb-4">Password Reset Successful</h1>
        <p class="text-gray-700 mb-6">Your password has been successfully reset.</p>
        <button onclick="window.location.href='login.php'"
                class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 w-full">
            Go to Login
        </button>
    </div>
</main>

</body>

</html>
