<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<main class="bg-gray-100 min-h-screen flex items-center justify-center">
    <div class="bg-white mx-auto p-8 rounded-md shadow-md w-full max-w-sm">
        <h1 class="text-2xl font-semibold text-center mb-4">Reset Password</h1>
        <form action="services/user/proccess-reset-password.php" method="POST">
            <input type="hidden" name="token" value="<?= htmlspecialchars($_SESSION['token']) ?>">
            <div class="mb-6">
                <label for="new-password" class="block pb-1 text-sm font-medium text-gray-700">New Password</label>
                <input type="password" id="new-password" name="new_password" placeholder="Enter new password"
                       class="mt-1 p-3 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div class="mb-6">
                <label for="confirm-password" class="block pb-1 text-sm font-medium text-gray-700">Confirm Password</label>
                <input type="password" id="confirm-password" name="confirm_password" placeholder="Confirm new password"
                       class="mt-1 p-3 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>
            <div class="flex justify-between items-center">
                <button type="button" onclick="window.location.href='previous-page.html'"
                        class="bg-gray-300 text-gray-700 py-2 px-4 rounded-md hover:bg-gray-400 focus:outline-none focus:bg-gray-400 w-1/2">
                    Cancel
                </button>
                <div class="w-1/2 pl-4">
                    <button type="submit"
                            class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700 w-full">
                        Reset Password
                    </button>
                </div>
            </div>
            <p class="pt-4 text-sm text-gray-700 text-red-400"><?= getFlashMessage("reset-password-response")?></p>
        </form>
    </div>
</main>

</body>

</html>
