<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>

<body>

<main class="bg-gray-100 min-h-screen flex items-center justify-center">
    <div class="bg-white mx-auto p-8 rounded-md shadow-md w-full max-w-sm">
        <h1 class="text-2xl font-semibold text-center mb-4">Reset Password</h1>
        <p class="text-gray-700 text-center mb-6">Enter your email and reset password link will be sent to your account.</p>
        <form action="services/user/send-reset-password.php" method="POST">
            <div class="mb-6">
                <label for="email" class="block pb-1 text-sm font-medium text-gray-700">Email Address</label>
                <input type="email" id="email" name="email" placeholder="Enter your email address"
                       class="mt-1 p-3 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
            </div>

            <div class="flex items-center justify-between">
                <button type="submit"
                        class="bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:bg-indigo-700">
                    Send Link
                </button>
                <button type="button" onclick="window.history.back()"
                    <a href="" id="resend-code" class="text-sm text-gray-600 hover:text-indigo-600">Cancel</a>
                </button>

            </div>
        </form>
        <?php if (isset($_SESSION['is-password-reset-email-valid'])): ?>
            <?php if ($_SESSION['is-password-reset-email-valid']): ?>
                <!-- Display the success message when is-resend-successful is true -->
                <p class="pt-3 text-sm">Reset password link is successfully sent to your email address!</p>
            <?php else: ?>
                <!-- Display the failure message when is-resend-successful is false -->
                <p class="pt-3 text-sm">Please enter valid email address.</p>
            <?php endif; ?>

        <?php endif; ?>
    </div>
</main>

</body>

</html>
