<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>


<body class="">

<!-- Navbar -->
<?php include "navigation.phtml"; ?>

<!-- Main Content -->
<main class="container mx-auto md:max-w-screen-xl mt-8 px-4">
    <div class=" m-auto">
        <h2 class="text-md md:text-lg font-bold mb-3">Veselin Sevo 23/22</h2>
        <img class="w-64" src="../../public/img/my-image.jpg" alt="Author image">
    </div>

</main>
</body>

</html>
