<!DOCTYPE html>
<html lang="en">

<?php require "public/head.phtml"; ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>


<body class="">

<!-- Navbar -->
<?php include "navigation.phtml"; ?>

<!-- Main Content -->
<main class="container mx-auto md:max-w-screen-xl mt-8 px-4 mb-10">
    <div class="flex flex-col md:flex-row justify-between">
        <!-- Toggle Filters Button (Icon) -->
        <div class="flex justify-end">
            <button id="toggleFiltersBtn" class="block md:hidden">
                <i class="fas fa-filter"></i> <!-- Font Awesome icon for filter -->
            </button>
        </div>
        <!-- Filters -->
        <div class="w-3/4 p-4 mx-auto bg-white rounded-md md:mr-4 hidden md:block md:w-1/4" id="filtersSection">
            <h2 class="text-xl font-semibold mb-4">Filters</h2>
            <div class="mb-4">
                <form id="searchForm" action="" method="GET">
                    <label for="search" class="block text-sm font-medium text-gray-700 mb-2">Search Property</label>
                    <input type="text" name="search" id="search" placeholder="Search properties" value="<?php echo htmlspecialchars($_GET['search'] ?? '', ENT_QUOTES); ?>" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                    <button type="submit" class="mt-4 text-sm md:text-sm bg-indigo-600 text-white py-2 px-4 rounded-md">Search</button>
                </form>
            </div>
            <hr class="mb-4">
            <div class="mb-4">
                <label for="typeFilter" class="block text-sm font-medium text-gray-700 mb-2">Property Type</label>
                <select id="typeFilter" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                    <option value="">All</option>
                    <option value="House">House</option>
                    <option value="Apartment">Apartment</option>
                    <option value="Condo">Condo</option>
                </select>
            </div>
            <div class="mb-4">
                <label for="countryFilter" class="block text-sm font-medium text-gray-700 mb-2">Country</label>
                <select id="countryFilter" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                </select>
            </div>
            <div class="mb-4">
                <label for="cityFilter" class="block text-sm font-medium text-gray-700 mb-2">City</label>
                <select id="cityFilter" class="w-full h-10 border-gray-300 p-2 disabled rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                    <option value="">All</option>
                    <option value="New York">New York</option>
                    <option value="Los Angeles">Los Angeles</option>
                    <option value="Chicago">Chicago</option>
                    <!-- Add more cities if needed -->
                </select>
            </div>
            <div class="mb-4">
                <label class="block text-sm font-medium text-gray-700 mb-2">Price</label>
                <div class="mb-4 flex gap-5">
                    <div>
                        <input type="number" id="minPrice" min="0" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="Min Price">
                    </div>
                    <div>
                        <input type="number" id="maxPrice" min="0" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="Max Price">
                    </div>
                </div>
            </div>
            <div class="mb-4">
                <label class="block text-sm font-medium text-gray-700 mb-2">Size</label>
                <div class="mb-4 flex gap-5">
                    <div>
                        <input type="number" id="minSize" min="0" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="Min Size">
                    </div>
                    <div>
                        <input type="number" id="maxSize" min="0" class="w-full h-10 border-gray-300 p-2 rounded-md shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="Max Size">
                    </div>
                </div>
            </div>
            <div id="errorMsg" class="hidden text-red-500 text-sm mb-2"></div>
            <button class="text-sm md:text-sm bg-indigo-600 text-white py-2 px-4 rounded-md">Apply Filters</button>
        </div>

        <!-- Property Grid -->
        <div class="w-full relative pt-6 md:pt-12">
            <!-- Icon for displaying 4 properties in a row -->
            <div class="absolute top-4 right-16 flex gap-4 z-0">
                <button id="displayFourBtn" class="hidden md:block text-indigo-600 hover:text-indigo-600">
                    <i class="fas fa-th"></i> <!-- Font Awesome icon for grid view -->
                </button>

                <!-- Icon for displaying 3 property in a row -->
                <button id="displayThreeBtn" class="hidden md:block hover:text-indigo-600">
                    <i class="fas fa-bars"></i> <!-- Font Awesome icon for list view -->
                </button>
            </div>

            <div class="grid mx-auto grid-cols-1 md:grid-cols-4 lg:grid-cols-4 gap-4 items-start" id="properties-container">

            </div>

        </div>
    </div>
</main>

<!--promeniti u &&-->
<?php if (!empty($_SESSION['user']) && empty($_SESSION['user']['questionnaire_submitted_at'])) { ?>
<!--    <div id="modal" class="modal fixed inset-0 z-50 overflow-auto bg-gray-900 bg-opacity-50 flex justify-center items-center">-->
<!--        <div class="modal-content bg-white p-8 rounded-md">-->
<!--            <span class="close absolute top-4 right-4 text-gray-600 cursor-pointer">&times;</span>-->
<!--            <h2 class="text-2xl font-bold mb-4 text-indigo-700">Questionnaire</h2>-->
<!--            <h3 class="mb-5 text-lg font-medium text-gray-900 dark:text-white">What describes you the best?</h3>-->
<!--            <form id="question-form" action="../services/questionnaire/submit-questionnaire.php" method="post">-->
<!--                <div class="mb-6">-->
<!--                    <h3 class="mb-3 text-lg font-medium text-gray-900 dark:text-white">I am:</h3>-->
<!--                    <ul class="grid w-full gap-6 md:grid-cols-4">-->
<!--                        <li>-->
<!--                            <input type="radio" id="student-option" value="1" class="hidden peer" name="question1-answers">-->
<!--                            <label for="student-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block text-center">-->
<!--                                    <img src="public/questionnaire/img/student.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Student</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="radio" id="employer-option" value="2" class="hidden peer" name="question1-answers">-->
<!--                            <label for="employer-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block text-center">-->
<!--                                    <img src="public/questionnaire/img/employer.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Employer</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="radio" id="employee-option" value="3" class="hidden peer" name="question1-answers">-->
<!--                            <label for="employee-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block text-center">-->
<!--                                    <img src="public/questionnaire/img/employee.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Employee</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="radio" id="none-option" value="4" class="hidden peer" name="question1-answers">-->
<!--                            <label for="none-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block text-center">-->
<!--                                    <img src="public/questionnaire/img/none.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">None</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!---->
<!---->
<!--                <div class="mb-6">-->
<!--                    <h3 class="mb-3 text-lg font-medium text-gray-900 dark:text-white">I am:</h3>-->
<!--                    <ul class="grid w-full gap-6 md:grid-cols-4">-->
<!--                        <li>-->
<!--                            <input type="radio" id="buyer-option" value="5" class="hidden peer" name="question2-answers">-->
<!--                            <label for="buyer-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block">-->
<!--                                    <img src="public/questionnaire/img/buyer.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Buyer</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="radio" id="seller-option" value="6" class="hidden peer" name="question2-answers">-->
<!--                            <label for="seller-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block">-->
<!--                                    <img src="public/questionnaire/img/seller.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Seller</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!---->
<!---->
<!---->
<!--                <div class="mb-6">-->
<!--                    <h3 class="mb-3 text-lg font-medium text-gray-900 dark:text-white">I am looking for / selling:</h3>-->
<!--                    <ul class="grid w-full gap-6 md:grid-cols-4">-->
<!--                        <li>-->
<!--                            <input type="checkbox" id="apartment-option" value="7" class="hidden peer" name="question3-answers[]">-->
<!--                            <label for="apartment-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block">-->
<!--                                    <img src="public/questionnaire/img/apartment.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Apartment</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="checkbox" id="house-option" value="8" class="hidden peer" name="question3-answers[]">-->
<!--                            <label for="house-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block">-->
<!--                                    <img src="public/questionnaire/img/house.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">House</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <input type="checkbox" id="condo-option" value="9" class="hidden peer" name="question3-answers[]">-->
<!--                            <label for="condo-option" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">-->
<!--                                <div class="block">-->
<!--                                    <img src="public/questionnaire/img/condo.png" class="mx-auto"/>-->
<!--                                    <div class="w-full text-lg font-semibold text-center">Condo</div>-->
<!--                                </div>-->
<!--                            </label>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
<!---->
<!---->
<!---->
<!--                <button type="submit" class="bg-indigo-700 text-white py-2 px-4 rounded-md hover:bg-indigo-800 block">Submit</button>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->

    <div id="modal" class="modal fixed inset-0 z-50 overflow-auto bg-gray-900 bg-opacity-50 flex justify-center items-center">
        <div class="modal-content bg-white p-8 rounded-md">
            <span class="close absolute top-4 right-4 text-gray-600 cursor-pointer">&times;</span>
            <h2 class="text-2xl font-bold mb-4 text-indigo-700">Questionnaire</h2>
            <form id="question-form" action="../services/questionnaire/submit-questionnaire.php" method="post">
                <?php foreach ($questions as $question): ?>
                    <div class="mb-6">
                        <h3 class="mb-5 text-lg font-medium text-gray-900 dark:text-white"><?= $question['text'] ?></h3>

                        <ul class="grid w-full gap-6 md:grid-cols-4">
                            <?php foreach ($answers[$question['id']] as $answer): ?>
                                <li>
                                    <?php if ($question['type'] === 'single_choice'): ?>
                                        <input type="radio" id="answer<?= $answer['id'] ?>" value="<?= $answer['id'] ?>" name="question<?= $question['id'] ?>-answers" class="hidden peer">
                                    <?php elseif ($question['type'] === 'multiple_choice'): ?>
                                        <input type="checkbox" id="answer<?= $answer['id'] ?>" value="<?= $answer['id'] ?>" name="question<?= $question['id'] ?>-answers[]" class="hidden peer">
                                    <?php endif; ?>
                                    <?php if (!empty($answer['image_name'])): ?>
                                        <label for="answer<?= $answer['id'] ?>" class="inline-flex items-center justify-center w-full p-5 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-indigo-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                                            <div class="block">
                                                <img src="public/questionnaire/img/<?= $answer['image_name'] ?>" alt="<?= $answer['text'] ?>" class="mx-auto">
                                            </div>
                                            <div class="w-full text-lg font-semibold text-center"><?= $answer['text'] ?></div>
                                        </label>
                                    <?php endif; ?>
                                    <br>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
                <button type="submit" class="bg-indigo-700 text-white py-2 px-4 rounded-md hover:bg-indigo-800 block">Submit</button>

            </form>
        </div>
    </div>
<?php } ?>


<script>
    // Display the modal
    var modal = document.getElementById('modal');
    function showModal() {
        modal.style.display = 'flex';
    }

    // Close the modal
    function closeModal() {
        modal.style.display = 'none';
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(e) {
        e.stopPropagation()
        console.log(e.target)
        if (e.target == modal) {
            closeModal()
        }
    }

    if(modal) {
        showModal()
    }

    let selectedCurrency = '<?php echo $_SESSION['user-settings']['currency']; ?>';
    let selectedCardsPerRow = '<?php echo $_SESSION['user-settings']['cards_per_row']; ?>';
</script>

<script type="module" src="public/js/index.js"></script>
</body>

</html>
