<nav class="bg-gray-100 p-4 shadow-lg">
    <div class="container md:max-w-screen-xl mx-auto flex justify-between items-center">
        <!-- Logo -->
        <a href="index.php" class="text-xl font-semibold text-gray-800"><img class="w-8 h-auto" src="public/img/realestate-logo.png"></a>

        <?php if (isset($_SESSION["fullname"])): ?>
            <!-- Display the "Hello [name]!" message -->
            <p class="md:ml-3">Hello <span class="font-medium text-indigo-600"><?php echo getFlashMessage("fullname") ?></span>!</p>
        <?php endif; ?>
        <!-- Responsive Navbar Toggler -->
        <button id="toggleMenuBtn" class="block md:hidden focus:outline-none">
            <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
        </button>

        <!-- Navbar Links (Hidden on small screens) -->
        <div id="menu" class="hidden md:flex flex-grow items-center justify-end">
            <a href="index.php" class="text-gray-600 hover:text-gray-800 mx-4 p-2">Home</a>
            <?php if (isLoggedIn()): ?>
                <a href="add-property.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Add property</a>
            <?php endif; ?>
            <?php if (isLoggedIn()): ?>
                <a href="my-properties.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">My properties</a>
            <?php endif; ?>

            <?php if (isAdmin()): ?>
                <a href="statistics.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Statistics</a>
            <?php endif; ?>

            <?php if (isAdmin()): ?>
                <a href="admin-panel.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Admin Panel</a>
            <?php endif; ?>
            <a href="contact.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Contact</a>
            <a href="author.php" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Author</a>
            <a href="Veselin Sevo 23_22 PHP 1 Dokumentacija.pdf" class="text-gray-600 hover:text-gray-800 mx-3 p-2">Documentation</a>
            <?php if (!isset($_SESSION["user"])): ?>
                <a href="login.php" class="hover:bg-gray-400 bg-gray-300 rounded-md mx-1 border-indigo-600 text-indigo-600 p-2">Login</a>
                <a href="register.php" class="hover:bg-indigo-700 rounded-md mx-4 bg-indigo-600 text-white p-2">Register</a>

            <?php else: ?>

                <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>

                    <div x-data="{ open: false }" class="bg-white dark:bg-gray-800 w-64 rounded-md shadow flex justify-center items-center">
                        <div @click="open = !open" class="relative z-10 border-b-4 border-transparent py-3" :class="{'border-indigo-700 transform transition duration-300 ': open}" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100">
                            <div class="flex justify-center items-center space-x-3 cursor-pointer">
                                <div class="rounded-full overflow-hidden border-2 dark:border-white border-gray-900">
                                    <img src="" alt="User Image" class="w-9 h-9 rounded-full userImg">                                </div>
                                <div class="font-semibold dark:text-white text-gray-900 text-lg">
                                    <div class="cursor-pointer"><?= $_SESSION["user"]['full_name'] ?></div>
                                </div>
                            </div>
                            <div x-show="open" class="absolute w-52 px-5 py-3 dark:bg-gray-800 bg-white rounded-lg shadow border dark:border-transparent mt-5 z-10">
                                <ul class="space-y-3 dark:text-white">
                                    <li class="font-medium">
                                        <a href="account.php" class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-indigo-700">
                                            <div class="mr-3">
                                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
                                            </div>
                                            Account
                                        </a>
                                    </li>
                                    <li class="font-medium">
                                        <a href="account.php" class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-indigo-700">
                                            <div class="mr-3">
                                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                                            </div>
                                            Setting
                                        </a>
                                    </li>
                                    <hr class="dark:border-gray-700">
                                    <li class="font-medium">
                                        <a href="services/user/logout.php"  class="flex items-center transform transition-colors duration-200 border-r-4 border-transparent hover:border-red-600">
                                            <div class="mr-3 text-red-600">
                                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
                                            </div>
                                            Logout
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
            <?php endif; ?>
        </div>
    </div>
</nav>

<!-- Mobile Menu -->
<div id="mobileMenu" class="md:hidden fixed inset-0 bg-gray-100 z-50 hidden">
    <div class="flex flex-col h-full justify-center items-center over">
        <a href="index.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4">Home</a>
        <a href="contact.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Contact</a>
        <a href="author.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Author</a>
        <a href="Veselin Sevo 23_22 PHP 1 Dokumentacija.pdf" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Documentation</a>
        <?php if (isLoggedIn()): ?>
            <a href="add-property.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Add property</a>
        <?php endif; ?>
        <?php if (isLoggedIn()): ?>
            <a href="my-properties.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">My properties</a>
        <?php endif; ?>
        <?php if (isAdmin()): ?>
            <a href="statistics.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Statistics</a>
        <?php endif; ?>
        <?php if (isAdmin()): ?>
            <a href="admin-panel.php" class="text-lg text-gray-600 hover:text-gray-800 mb-4 p-2">Admin Panel</a>
        <?php endif; ?>

        <?php if (!isLoggedIn()): ?>
            <a href="login.php" class="hover:bg-gray-400 bg-gray-300 rounded-md mx-4 border-indigo-600 text-indigo-600 p-2 mb-4">Login</a>
            <a href="register.php" class="hover:bg-indigo-700 rounded-md mx-4 bg-indigo-600 text-white p-2  mb-4">Register</a>
        <?php else: ?>
            <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>

            <a href="account.php">
                <div class="bg-white dark:bg-gray-800 w-64 rounded-md shadow flex justify-center items-center">
                    <div class="border-b-4 border-transparent py-3">
                        <div class="flex justify-center items-center space-x-3 cursor-pointer">
                            <div class="rounded-full overflow-hidden border-2 dark:border-white border-gray-900">
                                <img src="" alt="User Image" class="w-9 h-9 rounded-full userImg">                                </div>
                            <div class="font-semibold dark:text-white text-gray-900 text-lg">
                                <div class="cursor-pointer"><?= $_SESSION["user"]['full_name'] ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>

        <?php endif; ?>
        <p class="hidden">Name: <span id="userName"><?php echo $_SESSION['user']['full_name']; ?></span></p>
        <button id="closeMenuBtn" class="absolute top-0 right-0 text-3xl mt-8 mr-8 text-gray-700 hover:text-indigo-600 focus:outline-none">
            <i class="fa-solid fa-xmark"></i>
        </button>
    </div>
</div>
<script>
    const userFullName = <?php echo json_encode($_SESSION['full_name']); ?>//;

</script>
<script src="public/js/navigation.js"></script>
