<!DOCTYPE html>
<html lang="en">
<?php require "public/head.phtml"; ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

<body class="bg-gray-100">

<!-- Navbar -->
<?php require "public/navigation.phtml"; ?>

<main class="container mx-auto md:max-w-screen-xl mt-8 px-4">
    <div class="flex flex-col md:flex-row justify-between">
        <!-- Property Grid -->
        <div class="w-full relative pt-6 md:pt-12">
            <!-- Icon for displaying 4 properties in a row -->
            <button id="displayFiveBtn" class="absolute top-4 right-16 hidden md:block text-indigo-600 hover:text-indigo-600">
                <i class="fas fa-th"></i> <!-- Font Awesome icon for grid view -->
            </button>

            <!-- Icon for displaying 3 property in a row -->
            <button id="displayFourBtn" class="absolute top-4 right-4 hidden md:block hover:text-indigo-600">
                <i class="fas fa-bars"></i> <!-- Font Awesome icon for list view -->
            </button>
            <div class="grid mx-auto grid-cols-1 md:grid-cols-5 lg:grid-cols-5 gap-4 items-start" id="properties-container">

            </div>
            <div id="no-properties-message" class="flex flex-col align-middle gap-3">
                <h2 class="text-center md:text-left text-lg md:text-2xl font-bold mb-3 md:pl-4">You don't have any properties, yet.</h2>
                <a href="add-property.php" class="text-sm text-center md:text-base w-36 m-2 md:m-4 px-4 py-2 rounded-md bg-indigo-600 leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add property</a>
            </div>

        </div>
    </div>
</main>

<script>
    let selectedCurrency = '<?php echo $_SESSION['user-settings']['currency']; ?>';
    let selectedCardsPerRow = <?php echo $_SESSION['user-settings']['cards_per_row']; ?>;
    let userId = <?php echo $_SESSION['user']['id']; ?>;
</script>
<script type="module" src="public/property/js/my-properties.js"></script>
<script src="https://cdn.tailwindcss.com/"></script>
</body>
</html>
